volumes:
    db:

services:
    nginx:
        container_name: sale-system-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./.docker/nginx/default.d/:/etc/nginx/conf.d/
        networks:
          - sale-system

    app:
        container_name: rsus-api
        build:
            args:
              user: ${DOCKER_USER_ID:-0}
              uid: ${DOCKER_GROUP_ID:-0}
            context: .
            dockerfile: Dockerfile
        image: sale-system-api
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - .:/var/www
        networks:
          - sale-system

    db:
        container_name: sale-system-db
        image: postgres:15
        restart: unless-stopped
        environment:
            POSTGRES_USER: root
            POSTGRES_DB: sale-system
            POSTGRES_HOST_AUTH_METHOD: trust
        volumes:
            - db:/var/lib/postgresql/data
        ports:
          - ${DOCKER_DB_PORT}:5432
        networks:
          - sale-system

    cache:
        container_name: sale-system-redis
        image: redis:latest
        ports:
            - "6379:6379"
        networks:
            - sale-system


    mailhog:
        container_name: sale-system-mailhog
        image: 'mailhog/mailhog:latest'
        ports:
            - ${DOCKER_MAIL_SMTP_PORT}:1025
            - ${DOCKER_MAIL_HTTP_PORT}:8025
        networks:
            - sale-system

networks:
    sale-system:
        driver: bridge
